site_name: HMR Tutorial
theme: 'material'
pages:
- Inicio: index.md
- Creación del bundle: bundle.md
- Instalación y configuración de webpack-dev-server: webpackdevserver.md
- Compilando desde ES6: babel.md
- Configurando Hot Module Replacement: hrm.md
- OnsenUI, React, babel-preset-react y react-hot-loader: react.md